#%RAML 0.8
---
title: My API
version: 1.0
baseUri: http://localhost:8080/api/{version}

/dateTime:
  displayName: dateTime
  description: Gets the server dateTime
  get:
    responses: 
      200:
        body: 
          application/json: 
            example: |
              {
                "dateTime": "2016-04-26T19:29:35.857-07:00"
              }